import { useEffect, useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { FaCompass, FaMusic, FaArrowRight } from "react-icons/fa";
import { apiUrl } from "../../config/api";
import NativeAudioPlayer from "../../components/NativeAudioPlayer/NativeAudioPlayer";
import ProjectDiscussion from "../../components/ProjectDiscussion/ProjectDiscussion";
import "./Explore.css";
type Project={id:string;title:string;description?:string;hashtags?:string[];mode?:"regular"|"osl";inspired_by_artist_name?:string};
export default function Explore(){const[projects,setProjects]=useState<Project[]>([]);const[loading,setLoading]=useState(true);const navigate=useNavigate();useEffect(()=>{axios.get(`${apiUrl}/api/projects/explore/public`,{withCredentials:true}).then(({data})=>setProjects(data)).catch(()=>setProjects([])).finally(()=>setLoading(false));},[]);return <main className="explore-page"><p className="explore-kicker">OPENSYNQ / ALL OPEN SESSIONS</p><h1><FaCompass/> Explore the field</h1><p className="explore-intro">Every public project lives here—Outside Lands V1s and open Studio Circles alike.</p>{loading?<p>Loading open projects…</p>:projects.length?<div className="explore-grid">{projects.map(project=><article key={project.id} className="explore-card" onClick={()=>navigate(`/project/${project.id}`)}><span className="explore-mode">{project.mode==="osl"?"OUTSIDE LANDS V1":"STUDIO CIRCLE"}</span><FaMusic/><h2>{project.title}</h2><p>{project.description||"Open the session, hear the current version, and add your own build."}</p>{project.inspired_by_artist_name&&<b>Inspired by {project.inspired_by_artist_name}</b>}<div>{project.hashtags?.slice(0,3).map(tag=><b key={tag}>#{tag}</b>)}</div><div onClick={(event)=>event.stopPropagation()}><NativeAudioPlayer src={`${apiUrl}/api/projects/${project.id}/audio`} label={`Preview ${project.title}`}/></div><button>Open project <FaArrowRight/></button><ProjectDiscussion projectId={project.id} compact /></article>)}</div>:<div className="explore-empty"><FaMusic/><h2>No open projects yet</h2><p>Public Studio Circles and Outside Lands V1s will appear here.</p></div>}</main>}
